/**
 * Certificate Generation Utility
 * Generates shareable certificates for quiz completions
 */

export interface CertificateData {
	studentName: string
	courseName: string
	quizTitle: string
	score: number
	isPassed: boolean
	completedAt: Date
	attemptNumber: number
}

/**
 * Generate a text-based certificate for sharing
 */
export function generateTextCertificate(data: CertificateData): string {
	const border = '═'.repeat(60)
	const date = data.completedAt.toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'long',
		day: 'numeric'
	})

	return `
╔${border}╗
║${' '.repeat(60)}║
║${center('🎓 CERTIFICATE OF COMPLETION 🎓', 60)}║
║${' '.repeat(60)}║
╠${border}╣
║${' '.repeat(60)}║
║${center('This is to certify that', 60)}║
║${' '.repeat(60)}║
║${center(data.studentName.toUpperCase(), 60)}║
║${' '.repeat(60)}║
║${center('has successfully completed', 60)}║
║${' '.repeat(60)}║
║${center(`"${data.quizTitle}"`, 60)}║
║${' '.repeat(60)}║
║${center(`in the course: ${data.courseName}`, 60)}║
║${' '.repeat(60)}║
╠${border}╣
║${' '.repeat(60)}║
║${center(`Score: ${Math.round(data.score)}%`, 60)}║
║${center(`Status: ${data.isPassed ? 'PASSED ✓' : 'COMPLETED'}`, 60)}║
║${center(`Attempt #${data.attemptNumber}`, 60)}║
║${center(`Date: ${date}`, 60)}║
║${' '.repeat(60)}║
╚${border}╝

Generated by Open-EDU Learning Platform
`.trim()
}

/**
 * Generate HTML certificate for download
 */
export function generateHTMLCertificate(data: CertificateData): string {
	const date = data.completedAt.toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'long',
		day: 'numeric'
	})

	return `
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Certificate - ${data.studentName}</title>
	<style>
		* {
			margin: 0;
			padding: 0;
			box-sizing: border-box;
		}
		body {
			font-family: 'Georgia', serif;
			background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
			min-height: 100vh;
			display: flex;
			align-items: center;
			justify-content: center;
			padding: 2rem;
		}
		.certificate {
			background: white;
			max-width: 800px;
			width: 100%;
			padding: 3rem;
			border: 15px solid #f0f0f0;
			box-shadow: 0 20px 60px rgba(0,0,0,0.3);
			position: relative;
		}
		.certificate::before {
			content: '';
			position: absolute;
			top: 20px;
			left: 20px;
			right: 20px;
			bottom: 20px;
			border: 2px solid #d4af37;
			pointer-events: none;
		}
		.header {
			text-align: center;
			margin-bottom: 2rem;
		}
		.header h1 {
			font-size: 2.5rem;
			color: #333;
			margin-bottom: 0.5rem;
			letter-spacing: 2px;
		}
		.header .subtitle {
			font-size: 1.2rem;
			color: #666;
			font-style: italic;
		}
		.recipient {
			text-align: center;
			margin: 3rem 0;
		}
		.recipient .label {
			font-size: 1rem;
			color: #666;
			margin-bottom: 0.5rem;
		}
		.recipient .name {
			font-size: 3rem;
			color: #333;
			font-weight: bold;
			border-bottom: 3px solid #d4af37;
			display: inline-block;
			padding: 0.5rem 2rem;
			margin-bottom: 2rem;
		}
		.achievement {
			text-align: center;
			margin: 2rem 0;
			line-height: 1.8;
		}
		.achievement .text {
			font-size: 1.2rem;
			color: #333;
		}
		.achievement .highlight {
			font-size: 1.5rem;
			color: #667eea;
			font-weight: bold;
			display: block;
			margin: 1rem 0;
		}
		.stats {
			display: flex;
			justify-content: space-around;
			margin: 3rem 0;
			padding: 2rem;
			background: #f8f9fa;
			border-radius: 8px;
		}
		.stat {
			text-align: center;
		}
		.stat .value {
			font-size: 2rem;
			color: #667eea;
			font-weight: bold;
		}
		.stat .label {
			font-size: 0.9rem;
			color: #666;
			margin-top: 0.5rem;
		}
		.badge {
			text-align: center;
			margin: 2rem 0;
		}
		.badge-icon {
			width: 100px;
			height: 100px;
			background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
			border-radius: 50%;
			display: inline-flex;
			align-items: center;
			justify-content: center;
			font-size: 3rem;
			box-shadow: 0 10px 30px rgba(102, 126, 234, 0.3);
		}
		.footer {
			text-align: center;
			margin-top: 3rem;
			padding-top: 2rem;
			border-top: 1px solid #ddd;
		}
		.footer .date {
			font-size: 1rem;
			color: #666;
			margin-bottom: 1rem;
		}
		.footer .platform {
			font-size: 0.9rem;
			color: #999;
		}
		@media print {
			body {
				background: white;
			}
			.certificate {
				box-shadow: none;
			}
		}
	</style>
</head>
<body>
	<div class="certificate">
		<div class="header">
			<h1>🎓 CERTIFICATE OF COMPLETION</h1>
			<div class="subtitle">This certifies that</div>
		</div>
		
		<div class="recipient">
			<div class="name">${escapeHtml(data.studentName)}</div>
		</div>
		
		<div class="achievement">
			<div class="text">has successfully completed</div>
			<div class="highlight">"${escapeHtml(data.quizTitle)}"</div>
			<div class="text">in the course</div>
			<div class="highlight">${escapeHtml(data.courseName)}</div>
		</div>
		
		<div class="stats">
			<div class="stat">
				<div class="value">${Math.round(data.score)}%</div>
				<div class="label">Final Score</div>
			</div>
			<div class="stat">
				<div class="value">${data.isPassed ? '✓ PASSED' : 'COMPLETED'}</div>
				<div class="label">Status</div>
			</div>
			<div class="stat">
				<div class="value">#${data.attemptNumber}</div>
				<div class="label">Attempt</div>
			</div>
		</div>
		
		<div class="badge">
			<div class="badge-icon">${data.isPassed ? '🏆' : '📜'}</div>
		</div>
		
		<div class="footer">
			<div class="date">Completed on ${date}</div>
			<div class="platform">Generated by Open-EDU Learning Platform</div>
		</div>
	</div>
</body>
</html>
`.trim()
}

/**
 * Generate shareable URL with certificate data
 */
export function generateShareableURL(data: CertificateData): string {
	const baseUrl = typeof window !== 'undefined' ? window.location.origin : ''
	const params = new URLSearchParams({
		name: data.studentName,
		course: data.courseName,
		quiz: data.quizTitle,
		score: String(Math.round(data.score)),
		status: data.isPassed ? 'passed' : 'completed'
	})
	return `${baseUrl}/certificate?${params.toString()}`
}

/**
 * Download certificate as HTML file
 */
export function downloadHTMLCertificate(data: CertificateData): void {
	const html = generateHTMLCertificate(data)
	const blob = new Blob([html], { type: 'text/html' })
	const url = URL.createObjectURL(blob)
	const a = document.createElement('a')
	a.href = url
	a.download = `certificate-${sanitizeFilename(data.studentName)}-${sanitizeFilename(data.quizTitle)}.html`
	document.body.appendChild(a)
	a.click()
	document.body.removeChild(a)
	URL.revokeObjectURL(url)
}

/**
 * Copy text certificate to clipboard
 */
export async function copyTextCertificate(data: CertificateData): Promise<void> {
	const text = generateTextCertificate(data)
	await navigator.clipboard.writeText(text)
}

// Helper functions
function center(text: string, width: number): string {
	const padding = Math.max(0, width - text.length)
	const leftPad = Math.floor(padding / 2)
	const rightPad = padding - leftPad
	return ' '.repeat(leftPad) + text + ' '.repeat(rightPad)
}

function escapeHtml(text: string): string {
	const div = document.createElement('div')
	div.textContent = text
	return div.innerHTML
}

function sanitizeFilename(text: string): string {
	return text
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '')
}
